server:
  port: 8080

spring:
  datasource:
    username: root
    password: Pancy!1234
    url: jdbc:mysql://47.104.197.179:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cl.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.springboot.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
